# Generated by Django 4.0.5 on 2022-06-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
