# Generated by Django 4.0.5 on 2022-06-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_passenger_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Start Time')),
                ('endTime', models.DateTimeField(verbose_name='End Time')),
                ('startLocation', models.CharField(max_length=100, verbose_name='Start Location')),
                ('endLocation', models.CharField(max_length=100, verbose_name='End Location')),
                ('totalDistance', models.FloatField(max_length=10, verbose_name='Total Distance')),
                ('passenger', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.passenger', verbose_name='Passenger ID')),
            ],
        ),
    ]
