# Generated by Django 4.0.5 on 2022-06-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='base.passenger', verbose_name='Passenger ID'),
        ),
    ]
